src/core/urls.py
from django.contrib import admin
from django.urls import path
from core import views
app_name = 'core'
urlpatterns = [
    path('',views.home,name='home'),
    path('Signup/',views.Sign_up,name='signup'),
    path('Signin/',views.signin,name='signin'),
    path('logout/',views.logout,name='logout'),
    path('setting/',views.setting,name='setting'),
    path('upload/',views.upload,name='upload'),
    path('profile/<str:username>',views.profile,name='profile'),
    path('like-post/<post_id>',views.like,name="like"),
    path('comment/',views.comment,name='comment'),
    path('delete/<post_id>',views.delete,name='delete'),
    path('del/<comment_slug>',views.dlcm,name='delcm'),
    path('search', views.search, name='search'),
]

src/social_media/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import  static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Profile - {{user_profile.username}}</title>
   <!-- <link rel="icon" href="images/fav.png" type="image/png" sizes="16x16"> -->
    
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
	
	</div>
	
	<section>
			<div class="feature-photo">
				<figure><img src="{% static 'images/resources/timeline-1.jpg' %}" alt=""></figure>
				<form>
					<div class="add-btn">
					<span style="color: white; font-size: 27px; margin-right: 520px;"><b><u><a href="/">Home</a></u></b></span>
					{% if posts == 0 %}
				    <span style="color: white; font-size: 27px;"><b>no post</b></span>
					{% elif posts == 1 %}
					<span style="color: white; font-size: 27px;"><b>{{posts}} Post</b></span>
					{% else %}
					<span style="color: white; font-size: 27px;"><b>{{posts}} Post</b></span>
					{% endif %}
					<span style="color: white; font-size: 27px;"><b>1.7m followers</b></span>
					<span style="color: white; font-size: 27px;"><b>3.5k following</b></span>
					<a href="" title="" data-ripple=""><button style="background-color: #ffc0cb; border: #ffc0cb;">Follow</button></a>
					
					</div>
				</form>

				<!-- <form class="edit-phto">
					<i class="fa fa-camera-retro"></i>
					<label class="fileContainer">
						Upload Cover Photo
					<input type="file"/>
					</label>
				</form> -->
				<div class="container-fluid">
					<div class="row merged">
						<div class="col-lg-2 col-sm-3">
							<div class="user-avatar">
								<figure>
									<img src="{{user_profile.images.url}}" style="height: 250px; width: 100%;" alt="">
									<form class="edit-phto">
										<i class="fa fa-camera-retro"></i>
										<label class="fileContainer">
											<a href="#account-settings">Upload Profile Photo</a>
										</label>
									</form>
								</figure>
							</div>
						</div>
						<div class="col-lg-10 col-sm-9">
							<div class="timeline-info">
								<ul>
									<li class="admin-name">
									  <h5 style="color: black;white-space: nowrap; width: 110px; font-size: 27px;"><b>{{user_profile.username}}</b> | <a href="{% url 'core:home' %}" style="font-size: 25px;">Home</a><!--<i class="fa fa-check-circle" style="color: #48dbfb;" aria-hidden="true"></i>--></h5>
									  <!--<span>Group Admin</span>-->
									</li>
									<!--<li>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Go live!</a>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Music</a>
										<a class="" href="emporium/index-3.html" title="" data-ripple="">Emporium</a>
										<a class="" href="fitness/index.html" title="" data-ripple="">Health Inspection</a>
										<a class="" href="settings/account-setting.html" title="" data-ripple="">Settings</a>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Upload</a>
										<a class="" href="time-line.html" title="" data-ripple="">time line</a>
										<a class="" href="timeline-photos.html" title="" data-ripple="">Photos</a>
										<a class="" href="timeline-videos.html" title="" data-ripple="">Videos</a>
										<a class="" href="timeline-friends.html" title="" data-ripple="">Friends</a>
										<a class="" href="timeline-groups.html" title="" data-ripple="">Groups</a>
										<a class="" href="about.html" title="" data-ripple="">about</a>
										<a class="" href="#" title="" data-ripple="">more</a>

									</li>-->
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section><!-- top area -->
		<section>
			<div class="bio">
				{{user_profile.bio}}
			</div>
		</section>
		
	<section>
		<div class="gap gray-bg">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="row" id="page-contents">
							<div class="col-lg-3">
								<aside class="sidebar static">	
								</aside>
							</div>
							<div class="col-lg-6">
								<div class="central-meta">
									<ul class="photos">
					{% for post in user_posts %}
										<li>
											<a class="strip" href="{{post.image.url}}" title="" data-strip-group="mygroup" data-strip-group-options="loop: false">
												<img src="{{post.image.url}}" style="height: 250px; width: 300px;" alt=""></a>
										</li>
				 	{% endfor %}
	
										
									</ul>
									<!--<div class="lodmore"><button class="btn-view btn-load-more"></button></div>-->
								</div><!-- photos -->
							</div><!-- centerl meta -->
							<div class="col-lg-3">
								<aside class="sidebar static">
									
								</aside>
							</div><!-- sidebar -->
						</div>	
					</div>
				</div>
			</div>
		</div>	
	</section>

	
	
	<script data-cfasync="false" src="{% static '../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script><script src="js/main.min.js"></script>
	<script src="{% static 'js/script.js' %}"></script>

</body>	


</html>

src/templates/search.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="favicon.png" rel="icon" type="image/png">
    <title>Search</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
            <form>
            {% csrf_token %}
            <header style="margin-top: -23px;">
                <div class="header_inner">
                    <div class="left-side">
                        <!-- Logo -->
                        <div id="logo" class=" uk-hidden@s">
                            <a href="/">
                                <!-- <b><h1 style="text-transform: uppercase;">Social Book</h1></b> -->
                            </a>
                        </div>

                        <!--<div class="triger" uk-toggle="target: #wrapper ; cls: sidebar-active">
                            <i class="uil-bars"></i>
                        </div>-->

                        <!-- <div class="header_search"> -->
                            
                                <input type="text" name="searching" placeholder="Search for username..">&nbsp; &nbsp;
                                <button type="submit"><i class="fa fa-search fa-1x"></i></button>
                            
                            <!-- <div class="icon-search">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                                </svg>
                            </div> -->
                        <!-- </div> -->

                    </div>
                    <div class="right-side lg:pr-4">
                        <!-- welcome user -->
                        <a href="#" class="">
                            Welcome <b name="" class="">{{user.username}}&nbsp; &nbsp; &nbsp;</b>
                        </a>


                        <!-- profile -->

                        <a href="#">
                            <img src="{{ user_profile.images.url }}" class="header-avatar" alt="">
                        </a>
                        <div uk-drop="mode: click;offset:9" class="header_dropdown profile_dropdown border-t">
                            <ul>
                                <li><a href="{% url 'core:setting' %}"> Account setting </a> </li>
                                <!-- <li><a href="explore.html">explore </a> </li> -->
                                <li><a href="{% url 'core:logout' %}"> Log Out</a></li>
                            </ul>
                        </div>

                    </div>
                </div>
            </header>
            </form>
            <div style="margin-left: 250px; margin-right: 250px;">
                
                <style>
                body{margin-top:20px;
                background-color: #eee;
                }

                .search-result-categories>li>a {
                    color: #b6b6b6;
                    font-weight: 400
                }

                .search-result-categories>li>a:hover {
                    background-color: #ddd;
                    color: #555
                }

                .search-result-categories>li>a>.glyphicon {
                    margin-right: 5px
                }

                .search-result-categories>li>a>.badge {
                    float: right
                }

                .search-results-count {
                    margin-top: 10px
                }

                .search-result-item {
                    padding: 20px;
                    background-color: #fff;
                    border-radius: 4px
                }

                .search-result-item:after,
                .search-result-item:before {
                    content: " ";
                    display: table
                }

                .search-result-item:after {
                    clear: both
                }

                .search-result-item .image-link {
                    display: block;
                    overflow: hidden;
                    border-top-left-radius: 4px;
                    border-bottom-left-radius: 4px
                }

                @media (min-width:768px) {
                    .search-result-item .image-link {
                        display: inline-block;
                        margin: -20px 0 -20px -20px;
                
                        width: 200px
                    }
                }

                @media (max-width:767px) {
                    .search-result-item .image-link {
                        max-height: 200px
                    }
                }

                .search-result-item .image {
                    max-width: 100%
                }

                .search-result-item .info {
                    margin-top: 2px;
                    font-size: 12px;
                    color: #999
                }

                .search-result-item .description {
                    font-size: 13px
                }

                .search-result-item+.search-result-item {
                    margin-top: 20px
                }

                @media (min-width:768px) {
                    .search-result-item-body {
                        margin-left: 200px
                    }
                }

                .search-result-item-heading {
                    font-weight: 400
                }

                .search-result-item-heading>a {
                    color: #555
                }

                @media (min-width:768px) {
                    .search-result-item-heading {
                        margin: 0
                    }
                }
                </style>

                <div class="container">
                <div class="row ng-scope">
                    <div class="col-md-3 col-md-push-9">
                        <h4>Results For <span class="fw-semi-bold"><b>{{searching}}</b></span></h4>
                        <br>
                        
                        <!-- <p class="text-muted fs-mini">Listed content is categorized by the following groups:</p> -->
                        <!-- <ul class="nav nav-pills nav-stacked search-result-categories mt">
                            <li><a href="#">Friends <span class="badge">34</span></a>
                            </li>
                            <li><a href="#">Pages <span class="badge">9</span></a>
                            </li>
                            <li><a href="#">Images</a>
                            </li>
                            <li><a href="#">Groups</a>
                            </li>
                            <li><a href="#">Globals <span class="badge">18</span></a>
                            </li>
                        </ul> -->
                    </div>
                    <div class="col-md-9 col-md-pull-3">
                        <!-- <p class="search-results-count">About 94 700 000 (0.39 sec.) results</p> -->
                        
                        {% for user in username_profile_list %}
                        <section class="search-result-item">
                            <a class="image-link" href="/profile/{{user.user}}"><img class="image" src="{{user.images.url}}">
                            </a>
                            <div class="search-result-item-body">
                                <div class="row">
                                    <div class="col-sm-9">
                                        <h4 class="search-result-item-heading"><a href="/profile/{{user.user}}"><b>@{{user.user}}</b></a></h4>
                                        <p class="info">{{user.address}}</p>
                                        <p class="description">{{user.bio}}</p>
                                    </div>
                                    <!-- <div class="col-sm-3 text-align-center">
                                        <p class="value3 mt-sm">$9, 700</p>
                                        <p class="fs-mini text-muted">PER WEEK</p><a class="btn btn-primary btn-info btn-sm" href="#">Learn More</a>
                                    </div> -->
                                </div>
                            </div>
                        </section>
                        {% endfor %}
                        
                        <!-- <div class="text-align-center">
                            <ul class="pagination pagination-sm">
                                <li class="disabled"><a href="#">Prev</a>
                                </li>
                                <li class="active"><a href="#">1</a>
                                </li>
                                <li><a href="#">2</a>
                                </li>
                                <li><a href="#">3</a>
                                </li>
                                <li><a href="#">4</a>
                                </li>
                                <li><a href="#">5</a>
                                </li>
                                <li><a href="#">Next</a>
                                </li>
                            </ul>
                        </div> -->
                    </div>
                </div>
                </div>
            </div>

        </div>

    </div>








 <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>  
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


    <script src="{% static '../../unpkg.com/ionicons%405.2.3/dist/ionicons.js' %}"></script>
</body>


</html>

src/templates/setting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/images/favicon.png' %}" rel="icon" type="image/png">
    <title>Settings</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">

</head>

<body>






    <div class="container m-auto">

        <h1 class="text-2xl leading-none text-gray-900 tracking-tight mt-3"> Account Setting | <a
                href="{% url 'core:home' %}">Home</a> </h1>
        <ul class="mt-5 -mr-3 flex-nowrap lg:overflow-hidden overflow-x-scroll uk-tab">
            <li class="uk-active"><a href="#">General</a></li>
        </ul>

        <div class="grid lg:grid-cols-3 mt-12 gap-8">
            <div>
                <h3 class="text-xl mb-2"> Basic</h3>
                <p></p>
            </div>
            <div class="bg-white rounded-md lg:shadow-lg shadow col-span-2">
                <form enctype="multipart/form-data" action="" method="post">
                    {% csrf_token %}
                    <div class="grid grid-cols-2 gap-3 lg:p-6 p-4">
                        <img src="{{proflie.images.url}}" alt="" style="width: 100px; height: 100px; border-radius: 100%;">
                        <h1 style="margin-top: 30px; font-size: 30px; margin-left: -160px;">{{proflie.nickname}}</h1>
                        {% for message in messages %}
                        <h3 style="color: #ff5353; font-weight: 700;">
                            {{message}}
                        </h3> 
                        {% endfor %}   
                        <div class="col-span-2">
                            <label for="">Username</label>
                            <input name="nickname" type="text" value="{{proflie.nickname}}"  placeholder="Your name.." class="shadow-none bg-gray-100">
                        </div>
                        <div class="col-span-2">
                            <label for="">Profile</label>
                            <input type="file" name="pic" placeholder="Your name.." class="shadow-none bg-gray-100">
                        </div>
                        <div class="col-span-2">
                            <label for="about">biography</label>
                            <textarea id="about"  name="bio" rows="3" class="shadow-none bg-gray-100">{{proflie.bio}}</textarea>
                        </div>
                        <div class="col-span-2">
                            <label for=""> Location</label>
                            <input type="text" value="{{proflie.address}}" name="loc" placeholder="" class="shadow-none bg-gray-100">
                        </div>

                    </div>
                    
                <div class="bg-gray-10 p-6 pt-0 flex justify-end space-x-3">
                    <button class="p-2 px-4 rounded bg-gray-50 text-red-500"> Cancel </button>
                    <button type="submit" class="button bg-blue-700"> Save </button>
                </div>

                </form>

            </div>

        </div>

    </div>

    </div>

    </div>




    <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


    <script src="{% static '../../unpkg.com/ionicons%405.2.3/dist/ionicons.js' %}"></script>
</body>

</html>

src/templates/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/images/favicon.png' %}" rel="icon" type="image/png">
    <title>sign in</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">

</head>

<body class="bg-gray-100">


    <div id="wrapper" class="flex flex-col justify-between h-screen">

        <!-- header-->
        <div class="bg-white py-4 shadow dark:bg-gray-800">
            <div class="max-w-6xl mx-auto">


                <div class="flex items-center lg:justify-between justify-around">

                    <a href="trending.html">
                       <b><h1 style="font-size: 1.5rem;">Socol</h1></b>
                    </a>

                    <div class="capitalize flex font-semibold hidden lg:block my-2 space-x-3 text-center text-sm">
                        
                        <a  href="{% url 'core:signup'  %}" class="bg-pink-500 pink-500 px-6 py-3 rounded-md shadow text-white">Register</a>
                    </div>

                </div>
            </div>
        </div>

        <!-- Content-->
        <div>
            <div class="lg:p-12 max-w-md max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-">
                <h1 class="lg:text-3xl text-xl font-semibold  mb-6"> Log in</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {% for message in messages %}
                    <h3 style="color: #ff5353; font-weight: 700;">
                        {{message}}
                    </h3> 
                    {% endfor %}   
                    <input type="text" name="username" placeholder="Username" class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <input type="password" name="password" placeholder="***********" class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <div class="flex justify-between my-4">
                        <div class="checkbox">
                            <input type="checkbox" id="chekcbox1" checked>
                            <label for="chekcbox1"><span class="checkbox-icon"></span>Remember Me</label>
                        </div>
                        <a href="#"> Forgot Your Password? </a>
                    </div>
                    <button type="submit" class="bg-gradient-to-br from-pink-500 py-3 rounded-md text-white text-xl to-red-400 w-full">Login</button>
                    <div class="text-center mt-5 space-x-2">
                        <p class="text-base"> Not registered? <a href="{% url 'core:signup'  %}" class=""> Create a account </a></p>
                    </div>
                </form>
            </div>
        </div>
        
        <!-- Footer -->

        <div class="lg:mb-5 py-3 uk-link-reset">
            <div class="flex flex-col items-center justify-between lg:flex-row max-w-6xl mx-auto lg:space-y-0 space-y-3">
                <div class="flex space-x-2 text-gray-700 uppercase">
                    <a href="#"> About</a>
                    <a href="#"> Help</a>
                    <a href="#"> Terms</a>
                    <a href="#"> Privacy</a>
                </div>
                <p class="capitalize"> © copyright 2020 by socol</p>
            </div>
        </div>

    </div>

    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


</body>


</html>

src/templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/images/favicon.png' %}" rel="icon" type="image/png">
    <title>sign up</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">

</head>

<body class="bg-gray-100">


    <div id="wrapper" class="flex flex-col justify-between h-screen">

        <!-- header-->
        <div class="bg-white py-4 shadow dark:bg-gray-800">
            <div class="max-w-6xl mx-auto">


                <div class="flex items-center lg:justify-between justify-around">

                    <a href="trending.html">
                        <b><h1 style="font-size: 1.5rem;">Itmabna</h1></b>
                    </a>

                    <div class="capitalize flex font-semibold hidden lg:block my-2 space-x-3 text-center text-sm">
                        
                        <a href="{% url 'core:signin' %}" class="bg-pink-500 pink-500 px-6 py-3 rounded-md shadow text-white">Login</a>
                    </div>

                </div>
            </div>
        </div>

        <!-- Content-->

        <div>
            <div class="lg:p-12 max-w-md max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-">
                <h1 class="lg:text-3xl text-xl font-semibold mb-6"> Sign up</h1>
                <!--<p class="mb-2 text-black text-lg"> Register to manage your account </p>-->
                <form action="" method="post">
                    {% csrf_token %}
                    {% for message in messages %}
                    <h3 style="color: #ff5353; font-weight: 700;">
                        {{message}}
                    </h3> 
                    {% endfor %}                 
                    <input name="email" type="email" placeholder="Email" class="bg-gray-200 mb-2 shadow-none  dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <input name="username" type="text" placeholder="Username" class="bg-gray-200 mb-2 shadow-none  dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <input name="pass1" type="password" placeholder="Password" class="bg-gray-200 mb-2 shadow-none  dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <input name="pass2" type="password" placeholder="Confirm Password" class="bg-gray-200 mb-2 shadow-none  dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <div class="flex justify-start my-4 space-x-1">
                        <div class="checkbox">
                            <input type="checkbox" id="chekcbox1" checked>
                            <label for="chekcbox1"><span class="checkbox-icon"></span> I Agree</label>
                        </div>
                        <a href="#"> Terms and Conditions</a>
                    </div>
                    <button type="submit" class="bg-gradient-to-br from-pink-500 py-3 rounded-md text-white text-xl to-red-400 w-full">Sign up</button>
                    <div class="text-center mt-5 space-x-2">
                        <p class="text-base"> Do you have an account? <a href="{% url 'core:signin' %}"> Login </a></p>
                    </div>
                </form>
            </div>
        </div>
        
        <!-- Footer -->

        <div class="lg:mb-5 py-3 uk-link-reset">
            <div class="flex flex-col items-center justify-between lg:flex-row max-w-6xl mx-auto lg:space-y-0 space-y-3">
                <div class="flex space-x-2 text-gray-700 uppercase">
                    <a href="#"> About</a>
                    <a href="#"> Help</a>
                    <a href="#"> Terms</a>
                    <a href="#"> Privacy</a>
                </div>
                <p class="capitalize"> © copyright 2020 by socol</p>
            </div>
        </div>

    </div>

    <!--<script>
        
        (function (window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' dark';
            }
        })(window, document);
    
    
        (function (window, document, undefined) {
    
            'use strict';
    
            // Feature test
            if (!('localStorage' in window)) return;
    
            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;
    
            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function (event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);
    
        })(window, document);
    </script>-->

    <!-- Scripts -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


</body>


</html>